---
- ansible.builtin.import_role:
    name: no_12.dotfiles.aur_package
  vars:
    aur_package_name: nerd-fonts-jetbrains-mono
  when: is_arch

- block:
    - name: Ensure cask-fonts homebrew repository is present
      community.general.homebrew_tap:
        name: homebrew/cask-fonts
        state: present

    - name: Ensure nerd_fonts_jetbrains_mono package is present
      community.general.homebrew_cask:
        name: font-jetbrains-mono-nerd-font
        install_options:
          - "appdir={{ ansible_env.HOME }}/Applications"
        state: present
  when: is_macos
