---
- name: Ensure tmux packages are present
  become: "{{ ansible_pkg_mgr != 'homebrew' }}"
  package:
    name:
      - tmux
    state: present

- name: Ensure Tmux Plugin Manager is present
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    depth: 1

- name: Ensure tmux.conf is present
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0644
