---
- name: Ensure packages are present
  become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  package:
    name:
      - ack
      - atool
      - bat
      - curl
      - fzf
      - git
      - htop
      - ranger
      - tree
      - vim
      - zsh
    state: present
  when: dotfiles_install_packages

- name: Get home directory
  shell: echo $HOME
  changed_when: false
  register: home

- name: Ensure common dotfiles are present
  copy:
    src: "{{ item }}"
    dest: "{{ home.stdout }}/{{ item }}"
    mode: 0644
  with_items:
    - .ackrc
    - .fzfrc

- name: Ensure git dotfiles are present
  include_tasks: git.yml

- name: Ensure ranger dotfiles are present
  include_tasks: ranger.yml
