---
- name: Ensures ranger config dir exists
  file:
    path: "{{ home.stdout }}/.config/ranger"
    state: directory
    recurse: yes

- name: Ensure ranger config files are present
  copy:
    src: "{{ item }}"
    dest: "{{ home.stdout }}/.config/ranger/"
    mode: 0644
  with_items:
    - ranger/commands.py
    - ranger/rc.conf
