---
- name: Fetch existing .gitconfig
  fetch:
    src: "{{ dotfiles_user.home }}/.gitconfig"
    dest: /tmp
    fail_on_missing: false
  changed_when: false
  register: fetched_gitconfig

- name: Parse git user.name
  set_fact:
    dotfiles_git_user_name: "{{ lookup('ini', 'name section=user file={{ fetched_gitconfig.dest }}') }}"
  when: fetched_gitconfig.dest is defined and dotfiles_git_user_name is undefined

- name: Parse git user.email
  set_fact:
    dotfiles_git_user_email: "{{ lookup('ini', 'email section=user file={{ fetched_gitconfig.dest }}') }}"
  when: fetched_gitconfig.dest is defined and dotfiles_git_user_email is undefined

- name: Ensure .gitconfig is present
  template:
    src: .gitconfig
    dest: "{{ dotfiles_user.home }}/.gitconfig"
    mode: 0644
    owner: "{{ dotfiles_user.uid }}"
    group: "{{ dotfiles_user.group }}"
