---
- name: Ensure packages are present
  become: yes
  package:
    name:
      - zsh
      - git
      - curl
    state: present

- name: Ensure user exists and zsh is the default shell
  become: yes
  user:
    name: "{{ dotfiles_username }}"
    shell: /usr/bin/zsh
  register: dotfiles_user

- name: Ensure zsh dotfiles are present
  include_tasks: zsh.yml

- name: Ensure git dotfiles are present
  include_tasks: git.yml
