---
- name: Ensure package is present
  become: yes
  package:
    name:
      - zsh
      - git
      - curl
    state: present

- name: Ensure zsh is the default shell
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
  register: zsh_user

- name: Ensure oh my zsh is present
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
  args:
    creates: "{{ zsh_user.home }}/.oh-my-zsh"

- name: Ensure powerlevel10k theme is present
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_user.home }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
    version: "{{ zsh_powerlevel10k_version }}"

- name: Ensure dot files exists
  copy:
    src: "{{ item }}"
    dest: "{{ zsh_user.home }}/{{ item }}"
    mode: 0644
  with_items:
    - .zshrc
    - .p10k.zsh
