---
- name: Ensure .zsh directory is present
  become: yes
  file:
    path: "{{ dotfiles_user.home }}/.zsh"
    state: directory
    mode: 0755
    owner: "{{ dotfiles_user.uid }}"
    group: "{{ dotfiles_user.group }}"

- name: Ensure zsh extensions are present
  include_tasks: zsh_extensions.yml
  loop:
    - repo: https://github.com/gradle/gradle-completion.git
      dest: gradle-completion
      version: "{{ dotfiles_zsh_gradle_completion_version }}"
    - repo: https://github.com/romkatv/powerlevel10k.git
      dest: powerlevel10k
      version: "{{ dotfiles_zsh_powerlevel10k_version }}"
  loop_control:
    loop_var: extension

- name: Ensure zsh dotfiles are present
  become: yes
  copy:
    src: "{{ item }}"
    dest: "{{ dotfiles_user.home }}/{{ item }}"
    mode: 0644
    owner: "{{ dotfiles_user.uid }}"
    group: "{{ dotfiles_user.group }}"
  with_items:
    - .zshrc
    - .p10k.zsh
