---
- name: Ensure .zsh directory is present
  file:
    path: "{{ home.stdout }}/.zsh"
    state: directory
    mode: 0755

- name: Ensure zsh extensions are present
  include_tasks: zsh_extensions.yml
  loop:
    - repo: https://github.com/gradle/gradle-completion.git
      dest: gradle-completion
      version: "{{ dotfiles_zsh_gradle_completion_version }}"
  loop_control:
    loop_var: extension
  when: dotfiles_zsh_install_external_extensions

- name: Ensure zsh dotfiles are present
  copy:
    src: "{{ item }}"
    dest: "{{ home.stdout }}/{{ item }}"
    mode: 0644
  with_items:
    - .zshrc
