---
- name: "Ensure zsh extension {{ extension.dest }} is present"
  become: yes
  git:
    repo: "{{ extension.repo }}"
    dest: "{{ dotfiles_user.home }}/.zsh/{{ extension.dest }}"
    depth: 1
    version: "{{ extension.version }}"
  notify: chown extension directory

- name: "Ensure zsh extension {{ extension.dest }} directory is owned by {{ dotfiles_user.name }}"
  meta: flush_handlers
