---
- name: "Ensure zsh extension {{ extension.dest }} is present"
  become: yes
  git:
    repo: "{{ extension.repo }}"
    dest: "{{ dotfiles_user.home }}/.zsh/{{ extension.dest }}"
    depth: 1
    version: "{{ extension.version }}"
  notify: chown zsh extension directory
