---
- name: Ensure alacritty Arch package is present
  become: true
  community.general.pacman:
    name: alacritty
    state: present
  when: is_arch

- block:
    - name: Ensure alacritty MacOS package is present
      community.general.homebrew_cask:
        name: alacritty
        install_options:
          - "appdir={{ ansible_env.HOME }}/Applications"
        state: present

    - name: Ensure alacritty is not quarantined because the app is not signed with a valid key
      ansible.builtin.command:
        cmd: "xattr -d com.apple.quarantine {{ ansible_env.HOME }}/Applications/Alacritty.app"
      register: _result
      changed_when: _result.rc == 0
      failed_when: >
        (_result.rc != 0) and
        ("No such xattr: com.apple.quarantine" not in _result.stderr)
  when: is_macos

- name: Ensure config is present
  ansible.builtin.template:
    src: alacritty.yml.j2
    dest: "{{ ansible_env.HOME }}/.alacritty.yml"
    mode: 0644
