---
- name: Ensure zsh package is present
  become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  ansible.builtin.package:
    name:
      - zsh
    state: present

- name: Ensure .zsh directory is present
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.zsh"
    state: directory
    mode: 0755

- name: Ensure zsh extensions are present
  ansible.builtin.include_tasks: zsh_extensions.yml
  loop:
    - repo: https://github.com/gradle/gradle-completion.git
      dest: gradle-completion
      version: "{{ zsh_gradle_completion_version }}"
    - repo: https://github.com/romkatv/powerlevel10k.git
      dest: powerlevel10k
      version: "{{ zsh_powerlevel10k_version }}"
  loop_control:
    loop_var: extension

- name: Ensure .zshrc is present
  ansible.builtin.template:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0644

- name: Ensure .p10k.zsh is present
  ansible.builtin.copy:
    src: .p10k.zsh
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
    mode: 0644
