---
- name: "Ensure zsh extension {{ extension.name }} is present"
  ansible.builtin.git:
    repo: "{{ extension.repo }}"
    dest: "{{ zsh_extensions_dir }}/{{ extension.name }}"
    depth: 1
    version: "{{ extension.version }}"
