---
- name: "Ensure zsh extension {{ extension.dest }} is present"
  ansible.builtin.git:
    repo: "{{ extension.repo }}"
    dest: "{{ ansible_env.HOME }}/.zsh/{{ extension.dest }}"
    depth: 1
    version: "{{ extension.version }}"
