---
- name: Ensure ripgrep package is present
  become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  ansible.builtin.package:
    name:
      - ripgrep
    state: present

- name: Ensure .ripgreprc file is present
  ansible.builtin.copy:
    src: .ripgreprc
    dest: "{{ ansible_env.HOME }}/.ripgreprc"
    mode: 0644
