---
- hosts: all
  pre_tasks:
    - import_tasks: tasks/arch_linux/paru.yml

    - name: Ensure AUR packages are present
      include_tasks: tasks/arch_linux/aur_package.yml
      loop:
        - direnv
        - nerd-fonts-jetbrains-mono
        - visual-studio-code-bin
      loop_control:
        loop_var: aur_package_name

  roles:
    - role: no_12.dotfiles.custom_keyboard_layout
    - role: no_12.dotfiles.zsh
    - role: no_12.dotfiles.vscode
    - role: no_12.dotfiles.dotfiles
      dotfiles_install_packages: true
    - role: no_12.dotfiles.alacritty
