---
- hosts: nopc
  pre_tasks:
    - import_tasks: tasks/arch_linux/paru.yml

    - name: Ensure AUR packages are present
      include_tasks: tasks/arch_linux/aur_package.yml
      loop:
        - direnv
        - nerd-fonts-jetbrains-mono
        - visual-studio-code-bin
      loop_control:
        loop_var: aur_package_name

- hosts: all
  roles:
    - role: no_12.dotfiles.custom_keyboard_layout
    - role: no_12.dotfiles.zsh
    - role: no_12.dotfiles.alacritty
    - role: no_12.dotfiles.vscode
    - role: no_12.dotfiles.dotfiles
      dotfiles_install_packages: true

- hosts: macbook
  tasks:
    - name: Ensure cask-fonts homebrew repository is present
      community.general.homebrew_tap:
        name: homebrew/cask-fonts
        state: present

    - name: Ensure homebrew packages are present
      community.general.homebrew:
        name:
          - direnv
        state: present

    - name: Ensure homebrew cask packages are present
      community.general.homebrew_cask:
        name:
          - docker
          - font-jetbrains-mono-nerd-font
        state: present
