---
- hosts: nopc
  roles:
    - role: no_12.dotfiles.paru
  tasks:
    - name: Ensure AUR packages are present
      include_tasks: tasks/arch_linux/aur_package.yml
      loop:
        - direnv
        - nerd-fonts-jetbrains-mono
        - visual-studio-code-bin
      loop_control:
        loop_var: aur_package_name

- hosts: all
  pre_tasks:
    - name: Ensure common packages are present
      become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
      package:
        name:
          - bat
          - curl
          - htop
          - shellcheck
          - vim
        state: present
  roles:
    - role: no_12.dotfiles.custom_keyboard_layout
    - role: no_12.dotfiles.zsh
    - role: no_12.dotfiles.fzf
    - role: no_12.dotfiles.ripgrep
    - role: no_12.dotfiles.git
    - role: no_12.dotfiles.alacritty
    - role: no_12.dotfiles.vscode

- hosts: macbook
  tasks:
    - name: Ensure cask-fonts homebrew repository is present
      community.general.homebrew_tap:
        name: homebrew/cask-fonts
        state: present

    - name: Ensure homebrew packages are present
      community.general.homebrew:
        name:
          - direnv
        state: present

    - name: Ensure homebrew cask packages are present
      community.general.homebrew_cask:
        name:
          - firefox
          - font-jetbrains-mono-nerd-font
          - keepassxc
        install_options:
          - "appdir={{ ansible_env.HOME }}/Applications"
        state: present
