---
- name: Ensure fzf package is present
  become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  ansible.builtin.package:
    name:
      - fzf
    state: present

- name: Ensure key-bindings and completion are present
  ansible.builtin.shell:
    cmd: $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-update-rc
    creates:
      - /opt/homebrew/opt/fzf/shell/key-bindings.zsh
      - /opt/homebrew/opt/fzf/shell/completion.zsh
  changed_when: false
  when: is_macos

- name: Ensure .fzfrc file is present
  ansible.builtin.copy:
    src: .fzfrc
    dest: "{{ ansible_env.HOME }}/.fzfrc"
    mode: 0644
