---
- name: Ensure fzf package is present
  become: "{{ true if ansible_pkg_mgr != 'homebrew' else false }}"
  ansible.builtin.package:
    name:
      - fzf
    state: present

- name: Ensure .fzfrc file is present
  ansible.builtin.copy:
    src: .fzfrc
    dest: "{{ ansible_env.HOME }}/.fzfrc"
    mode: 0644
