---
- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ vscode_user_config_directory }}"
    state: directory
    recurse: yes

- name: Ensure config is present
  ansible.builtin.template:
    src: settings.json.j2
    dest: "{{ vscode_user_config_file }}"
    mode: 0600

- name: List installed extensions
  ansible.builtin.command: code --list-extensions
  changed_when: false
  register: code_installed_extensions

- name: Ensure extensions are present
  ansible.builtin.command: "code --install-extension {{ item }}"
  when: item not in code_installed_extensions.stdout_lines
  with_items:
    - christian-kohler.path-intellisense
    - donjayamanne.githistory
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - gruntfuggly.todo-tree
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-python.vscode-pylance
    - redhat.ansible
    - redhat.vscode-yaml
    - sleistner.vscode-fileutils
    - streetsidesoftware.code-spell-checker
    - streetsidesoftware.code-spell-checker-german
    - timonwong.shellcheck
    # - ms-vscode.powershell
    # - gitlab.gitlab-workflow
