---
# TODO - name: Ensure vscode Linux package is present

- name: Ensure vscode MacOS package is present
  community.general.homebrew_cask:
    name: visual-studio-code
    install_options:
      - "appdir={{ ansible_env.HOME }}/Applications"
    state: present
  when: is_macos

- name: Ensure config dir exists
  ansible.builtin.file:
    path: "{{ vscode_user_config_directory }}"
    state: directory
    recurse: yes

- name: Ensure config is present
  ansible.builtin.template:
    src: settings.json.j2
    dest: "{{ vscode_user_config_file }}"
    mode: 0600

- name: List installed extensions
  ansible.builtin.command: "{{ vscode_binary }} --list-extensions"
  changed_when: false
  register: code_installed_extensions

- name: Ensure extensions are present
  ansible.builtin.command: "{{ vscode_binary }} --install-extension {{ item }}"
  when: item not in code_installed_extensions.stdout_lines
  with_items: "{{ vscode_extensions }}"
