FROM archlinux:latest

ENV ANSIBLE_USER=ansible

RUN pacman -Syu --noconfirm curl git python sudo zsh && \
    groupadd -r $ANSIBLE_USER && \
    useradd -m -g $ANSIBLE_USER $ANSIBLE_USER && \
    echo "${ANSIBLE_USER} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER $ANSIBLE_USER
