vscode_binary: "{{ ansible_env.HOME + '/Applications/Visual\\ Studio\\ Code.app/Contents/Resources/app/bin/code' if is_macos else 'code' }}"
vscode_user_config_directory: "{{ ansible_env.HOME }}/{{ 'Library/Application Support/Code/User' if is_macos else '.config/Code/User' }}"
vscode_common_extensions:
  - christian-kohler.path-intellisense
  - donjayamanne.githistory
  - eamodio.gitlens
  - esbenp.prettier-vscode
  - Gruntfuggly.todo-tree
  - ms-azuretools.vscode-docker
  - ms-python.python
  - ms-python.vscode-pylance
  - redhat.ansible
  - redhat.vscode-yaml
  - sleistner.vscode-fileutils
  - streetsidesoftware.code-spell-checker
  - streetsidesoftware.code-spell-checker-german
  - timonwong.shellcheck
vscode_extensions: "{{ vscode_common_extensions | union(vscode_extra_extensions) }}"
