---
- name: Ensure custom keyboard mapping script is present for MacOS
  ansible.builtin.import_tasks: macos.yml
  when: ansible_os_family == 'Darwin'

- name: Ensure custom keyboard mapping script is present for Archlinux
  ansible.builtin.import_tasks: xkb.yml
  when: ansible_os_family == 'Archlinux'
